### ISSUE TITLE
#!/bin/bash should be at the top of the file

### ISSUE THREAD

**Issue by zuranthus** [StefanBossbaly/CopperheadOS-Docker#5]
https://github.com/StefanBossbaly/CopperheadOS-Docker/blob/9272988d9bab943615b869fb3187fd441de1e1e8/src/docker_entrypoint.sh#L2

Maybe this will save you some debugging time :) If it is not at the top, the entry script doesn't recognize [[.

**Comment by StefanBossbaly** [comment]
Fixed in 4435f956890b94fd818a0b534f9b6478f7c1222f.

Yeah looks like I somehow switch the `#!/bin/bash` and `set -e` last night. Not getting enough sleep :sleeping:
